#!/bin/bash -e

APP=$1
if [ -z "${APP}" ]; then
	echo "Usage: $0 <application>"
	exit 1
fi

STATUS=$(juju status --format json)
MODEL=$(echo ${STATUS} | jq -r '.model.name')
CONTROLLER=$(echo ${STATUS} | jq -r '.model.controller')
NONCE=$(juju add-user --models ${MODEL} --controller ${CONTROLLER} agent-${APP} | grep register | awk '{print $3}')

juju set-config ${APP} juju-api-nonce=${NONCE}

echo "Application agent ${APP} authorized."
